using ApiProject.DatabaseAccess.Entities;

namespace ApiProject.Tests.CreateSeed;

public class SeederTopic
{
        public static List<SubjectAreaDataAccessModel> TopicForSeeding()
        {
                    var topicsToSeed = new List<SubjectAreaDataAccessModel>
                    {
                        new() { Title = "Künstliche Intelligenz (AI)", Description = "Methoden und Anwendungen zur Nachbildung intelligenter Verhaltensweisen durch Maschinen." },
                        new() { Title = "Maschinelles Lernen", Description = "Selbstlernende Algorithmen zur Mustererkennung und Vorhersage." },
                        new() { Title = "Deep Learning", Description = "Neuronale Netzwerke mit vielen Schichten für komplexe Lernaufgaben." },
                        new() { Title = "Computer Vision", Description = "Automatisierte visuelle Wahrnehmung und Bilderkennung durch Computer." },
                        new() { Title = "Natural Language Processing (NLP)", Description = "Verarbeitung und Analyse natürlicher Sprache durch Maschinen." },
                        new() { Title = "Big Data & Analytics", Description = "Analyse großer Datenmengen zur Entscheidungsunterstützung." },
                        new() { Title = "Data Mining", Description = "Extraktion von Mustern und Wissen aus großen Datensätzen." },
                        new() { Title = "Mobile App Entwicklung (Android/iOS)", Description = "Entwicklung von mobilen Anwendungen für Android und iOS." },
                        new() { Title = "Webentwicklung (Frontend/Backend)", Description = "Design und Implementierung moderner Webanwendungen." },
                        new() { Title = "Softwarearchitektur", Description = "Strukturierung und Entwurf komplexer Softwaresysteme." },
                        new() { Title = "Testautomatisierung", Description = "Automatisiertes Testen von Software zur Qualitätssteigerung." },
                        new() { Title = "Datenbanken & SQL", Description = "Datenmodellierung und Datenabfragen mit relationalen Systemen." },
                        new() { Title = "DevOps & CI/CD", Description = "Automatisierung und Integration im Softwareentwicklungsprozess." },
                        new() { Title = "Cloud Computing (AWS, Azure, GCP)", Description = "Skalierbare Infrastruktur- und Plattformlösungen in der Cloud." },
                        new() { Title = "IT-Sicherheit / Cybersecurity", Description = "Schutz von IT-Systemen gegen Angriffe und Bedrohungen." },
                        new() { Title = "Blockchain-Technologie", Description = "Verteilte Systeme zur sicheren Datenübertragung und Speicherung." },
                        new() { Title = "Edge Computing", Description = "Verarbeitung von Daten direkt an der Quelle zur Reduktion von Latenz." },
                        new() { Title = "Embedded Systems", Description = "Hardwarenahe Softwareentwicklung für spezialisierte Geräte." },
                        new() { Title = "AR/VR/XR-Anwendungen", Description = "Interaktive virtuelle und erweiterte Realitäten für Nutzererlebnisse." },
                        new() { Title = "Game Development", Description = "Konzeption und Entwicklung digitaler Spiele." },
                        
                        new() { Title = "Digital Business Transformation", Description = "Digitale Umgestaltung von Geschäftsmodellen und -prozessen." },
                        new() { Title = "E-Commerce", Description = "Online-Vertrieb von Produkten und Dienstleistungen." },
                        new() { Title = "Prozessautomatisierung (RPA)", Description = "Automatisierung repetitiver Geschäftsprozesse mit Software-Bots." },
                        new() { Title = "Controlling mit Power BI / Tableau", Description = "Visuelle Aufbereitung betrieblicher Kennzahlen." },
                        new() { Title = "CRM-Systeme & Kundenanalyse", Description = "Verwaltung und Analyse von Kundenbeziehungen." },
                        new() { Title = "IT-Projektmanagement", Description = "Planung und Steuerung von IT-Projekten." },
                        new() { Title = "Innovationsmanagement", Description = "Förderung und Strukturierung von Innovationsprozessen." },
                        new() { Title = "Wirtschaftsinformatik", Description = "Schnittstelle zwischen IT und BWL." },
                        new() { Title = "Finanztechnologie (FinTech)", Description = "Technologien im Finanzdienstleistungssektor." },
                        new() { Title = "Business Intelligence", Description = "Datengetriebene Geschäftsanalysen und Entscheidungsfindung." },

                        new() { Title = "Wissenschaftliches Arbeiten mit LaTeX", Description = "Professionelles Erstellen von Abschlussarbeiten mit LaTeX." },
                        new() { Title = "Interdisziplinäre Projektarbeit", Description = "Zusammenarbeit über Fachgrenzen hinweg in Projekten." },
                        new() { Title = "Agile Methoden (Scrum, Kanban)", Description = "Agile Vorgehensweisen im Projekt- und Produktmanagement." },
                        new() { Title = "Change Management", Description = "Begleitung von Veränderungsprozessen in Organisationen." },
                        new() { Title = "Ethik in der KI", Description = "Gesellschaftliche Verantwortung und Fairness in Algorithmen." },
                        new() { Title = "UX/UI Design", Description = "Benutzerzentriertes Gestalten digitaler Oberflächen." },
                        new() { Title = "Accessibility & Inclusive Design", Description = "Barrierefreies Design digitaler Produkte." },
                        new() { Title = "Smart Cities", Description = "Intelligente Städte durch IT-Infrastruktur." },
                        new() { Title = "Nachhaltige IT", Description = "Umweltbewusste IT-Lösungen und Energieeffizienz." },
                        new() { Title = "Medienrecht & Datenschutz (DSGVO)", Description = "Rechtsgrundlagen im Umgang mit digitalen Inhalten." },

                        // Zusätzliche Themen in Informatik, Medien und Kommunikation, Wirtschaft usw.
                        new() { Title = "Algorithmen und Datenstrukturen", Description = "Grundlagen effizienter Algorithmen und Datenorganisation." },
                        new() { Title = "Betriebssysteme", Description = "Funktionsweise und Verwaltung von Betriebssystemen." },
                        new() { Title = "Netzwerktechnik", Description = "Design und Sicherheit von Computernetzen." },
                        new() { Title = "Software Engineering", Description = "Methoden zur systematischen Softwareentwicklung." },
                        new() { Title = "Programmiersprachen (C#, Java, Python)", Description = "Vergleich und Anwendung populärer Programmiersprachen." },
                        new() { Title = "Human-Computer Interaction", Description = "Interaktion zwischen Menschen und Computern." },
                        new() { Title = "Robotik", Description = "Entwicklung und Steuerung von Robotern." },
                        new() { Title = "Quantencomputing", Description = "Grundlagen und Anwendungen der Quanteninformationsverarbeitung." },
                        new() { Title = "Internet of Things (IoT)", Description = "Vernetzung intelligenter Geräte und Sensoren." },
                        new() { Title = "Mikroservices", Description = "Architektur für skalierbare und modulare Anwendungen." },
                        new() { Title = "API-Entwicklung", Description = "Design und Implementierung von Application Programming Interfaces." },
                        new() { Title = "Versionskontrolle (Git)", Description = "Verwaltung von Code-Änderungen mit Git." },
                        new() { Title = "Containerisierung (Docker)", Description = "Isolierung und Bereitstellung von Anwendungen." },
                        new() { Title = "Kubernetes", Description = "Orchestrierung von Container-Anwendungen." },
                        new() { Title = "Reinforcement Learning", Description = "Lernalgorithmen durch Belohnung und Strafe." },
                        new() { Title = "Computer Graphics", Description = "Erzeugung und Manipulation visueller Inhalte." },
                        new() { Title = "Bioinformatik", Description = "Anwendung von IT in der Biologie und Medizin." },
                        new() { Title = "Kryptographie", Description = "Sichere Verschlüsselung und Datenschutz." },
                        new() { Title = "Ethik Hacking", Description = "Verantwortungsvolles Testen von Sicherheitssystemen." },
                        new() { Title = "Digitale Forensik", Description = "Untersuchung digitaler Beweise." },
                        new() { Title = "Cloud-Sicherheit", Description = "Schutz von Daten in Cloud-Umgebungen." },
                        new() { Title = "Datenschutz", Description = "Grundlagen des Datenschutzes und Privatsphäre." },
                        new() { Title = "Agile Entwicklung", Description = "Flexible Methoden in der Softwareentwicklung." },
                        new() { Title = "Test-Driven Development (TDD)", Description = "Entwicklung durch automatisierte Tests." },
                        new() { Title = "Behavior-Driven Development (BDD)", Description = "Spezifikation durch Verhaltensbeschreibungen." },
                        new() { Title = "Monitoring und Logging", Description = "Überwachung und Protokollierung von Systemen." },
                        new() { Title = "Performance-Optimierung", Description = "Verbesserung der Geschwindigkeit und Effizienz." },
                        new() { Title = "Skalierbarkeit", Description = "Anpassung von Systemen an wachsende Anforderungen." },
                        new() { Title = "Fehlertoleranz", Description = "Robustheit gegen Ausfälle und Fehler." },
                        new() { Title = "Design Patterns", Description = "Bewährte Lösungen für Softwareprobleme." },
                        new() { Title = "SOLID-Prinzipien", Description = "Grundregeln für sauberen Code." },
                        new() { Title = "MVC-Architektur", Description = "Modell-View-Controller für Anwendungsstruktur." },
                        new() { Title = "RESTful APIs", Description = "Entwicklung von REST-basierten Schnittstellen." },
                        new() { Title = "GraphQL", Description = "Flexible Abfragesprache für APIs." },
                        new() { Title = "WebSockets", Description = "Echtzeitkommunikation in Webanwendungen." },
                        new() { Title = "Progressive Web Apps", Description = "Web-Apps mit nativer App-Funktionalität." },
                        new() { Title = "Serverless Computing", Description = "Ausführung von Code ohne Serververwaltung." },
                        new() { Title = "Event-Driven Architecture", Description = "Architektur basierend auf Ereignissen." },
                        new() { Title = "Message Queues", Description = "Asynchrone Nachrichtenverarbeitung." },
                        new() { Title = "NoSQL-Datenbanken", Description = "Nicht-relationale Datenbanksysteme." },
                        new() { Title = "MongoDB", Description = "Dokumentenbasierte NoSQL-Datenbank." },
                        new() { Title = "Redis", Description = "In-Memory-Datenstruktur-Speicher." },
                        new() { Title = "Elasticsearch", Description = "Suchmaschine für Volltextsuche." },
                        new() { Title = "Supply Chain Management", Description = "Optimierung von Lieferketten." },
                        new() { Title = "Marketing Automation", Description = "Automatisierte Marketingkampagnen." },
                        new() { Title = "Digital Marketing", Description = "Online-Marketingstrategien." },
                        new() { Title = "SEO/SEM", Description = "Suchmaschinenoptimierung und -marketing." },
                        new() { Title = "Social Media Marketing", Description = "Marketing über soziale Netzwerke." },
                        new() { Title = "Content Management Systems", Description = "Systeme zur Verwaltung von Inhalten." },
                        new() { Title = "ERP-Systeme", Description = "Enterprise Resource Planning." },
                        new() { Title = "SAP", Description = "Unternehmenssoftware von SAP." },
                        new() { Title = "Salesforce", Description = "CRM- und Vertriebsplattform." },
                        new() { Title = "Data Warehousing", Description = "Zentralisierung von Daten für Analysen." },
                        new() { Title = "ETL-Prozesse", Description = "Extraktion, Transformation und Laden von Daten." },
                        new() { Title = "Predictive Analytics", Description = "Vorhersagemodelle mit Daten." },
                        new() { Title = "Machine Learning in Business", Description = "KI-Anwendungen in Unternehmen." },
                        new() { Title = "Blockchain in Finance", Description = "Kryptowährungen und Finanztransaktionen." },
                        new() { Title = "Regulatorische Compliance", Description = "Einhaltung gesetzlicher Vorschriften." },
                        new() { Title = "Risikomanagement", Description = "Identifikation und Minimierung von Risiken." },
                        new() { Title = "Portfolio-Management", Description = "Verwaltung von Investitionsportfolios." },
                        new() { Title = "Peer-to-Peer Lending", Description = "Direkte Kreditvergabe zwischen Personen." },
                        new() { Title = "Crowdfunding", Description = "Finanzierung durch die Crowd." },
                        new() { Title = "Insurance Technology (InsurTech)", Description = "Technologie in der Versicherungsbranche." },
                        new() { Title = "HealthTech", Description = "Technologie im Gesundheitswesen." },
                        new() { Title = "EdTech", Description = "Bildungstechnologie." },
                        new() { Title = "PropTech", Description = "Immobilientechnologie." },
                        new() { Title = "LegalTech", Description = "Technologie im Rechtsbereich." },
                        new() { Title = "RegTech", Description = "Regulatorische Technologie." },
                        new() { Title = "Digitale Medien", Description = "Erstellung und Verbreitung digitaler Inhalte." },
                        new() { Title = "Social Media Strategien", Description = "Planung und Umsetzung von Social-Media-Kampagnen." },
                        new() { Title = "Content Creation", Description = "Erstellung ansprechender Inhalte." },
                        new() { Title = "Video Production", Description = "Produktion von Videoinhalten." },
                        new() { Title = "Podcasting", Description = "Erstellung und Verbreitung von Podcasts." },
                        new() { Title = "Journalismus im Digitalen Zeitalter", Description = "Moderne Nachrichtenproduktion." },
                        new() { Title = "Public Relations", Description = "Öffentlichkeitsarbeit und Imagepflege." },
                        new() { Title = "Werbung", Description = "Strategien und Techniken der Werbung." },
                        new() { Title = "Branding", Description = "Aufbau und Pflege von Marken." },
                        new() { Title = "Medienrecht", Description = "Rechtliche Aspekte der Medien." },
                        new() { Title = "Urheberrecht", Description = "Schutz geistigen Eigentums." },
                        new() { Title = "Kommunikationstheorie", Description = "Theorien der menschlichen Kommunikation." },
                        new() { Title = "Massenkommunikation", Description = "Kommunikation mit großen Zielgruppen." },
                        new() { Title = "Multimedia Design", Description = "Gestaltung interaktiver Medien." },
                        new() { Title = "Grafikdesign", Description = "Visuelle Gestaltung von Inhalten." },
                        new() { Title = "Fotografie", Description = "Techniken der digitalen Fotografie." },
                        new() { Title = "Video Editing", Description = "Bearbeitung von Videomaterial." },
                        new() { Title = "Animation", Description = "Erstellung bewegter Bilder." },
                        new() { Title = "Virtual Reality in Media", Description = "VR-Anwendungen in der Medienbranche." },
                        new() { Title = "Augmented Reality in Media", Description = "AR für interaktive Erlebnisse." },
                        new() { Title = "Streaming Services", Description = "Plattformen für Video- und Audio-Streaming." },
                        new() { Title = "Influencer Marketing", Description = "Marketing durch Influencer." },
                        new() { Title = "Krisenkommunikation", Description = "Kommunikation in Krisensituationen." },
                        new() { Title = "Corporate Communication", Description = "Unternehmensinterne und -externe Kommunikation." },
                        new() { Title = "Event Management", Description = "Planung und Durchführung von Events." },
                        new() { Title = "Pressemitteilungen", Description = "Verfassen und Verteilen von Pressetexten." },
                        new() { Title = "Medienethik", Description = "Ethische Standards in den Medien." },
                        new() { Title = "Fake News Detection", Description = "Erkennung und Bekämpfung von Falschinformationen." },
                        new() { Title = "Data Journalism", Description = "Journalismus mit Datenanalyse." },
                    };
                    return topicsToSeed;

        }
}