@startuml ThesisManagementAPI-UseCaseDiagram

title Thesis Management API - Use Case Diagram

left to right direction

actor Student
actor Tutor
actor Admin

rectangle "Thesis Management System" {
    usecase "Manage Own Profile" as UC1
    usecase "Search for Topics" as UC2
    usecase "Apply for a Thesis" as UC3
    usecase "Submit Thesis" as UC4

    usecase "Manage Topics" as UC5
    usecase "Review Thesis Applications" as UC6
    usecase "Grade Thesis" as UC7

    usecase "Manage All Users" as UC8
    usecase "Manage All Theses" as UC9
    usecase "Manage All Topics" as UC10
}

Student --> (UC1)
Student --> (UC2)
Student --> (UC3)
Student --> (UC4)

Tutor --> (UC1)
Tutor --> (UC5)
Tutor --> (UC6)
Tutor --> (UC7)

Admin --> (UC8)
Admin --> (UC9)
Admin --> (UC10)

@enduml
